# This file configures the analyzer for Tenebralis Dream System

include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Suppress invalid_annotation_target for Freezed models
    # @JsonKey in factory constructor parameters is valid for Freezed
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # Prefer const constructors
    prefer_const_constructors: true
    prefer_const_declarations: true
    # Allow print for debugging (remove in production)
    avoid_print: false
